### ISSUE TITLE
DNS issue if using a cluster redis only on version above ( "NewLife.Redis" Version="5.1.2023.101")

### ISSUE THREAD

**Issue by ehinolakingsley** [NewLifeX/NewLife.Redis#110]
System.AggregateException: One or more errors occurred. (解析主机redis-replicas-0.的地址失败！Name does not resolve)
2023-09-09T21:11:46.269655908Z  ---> NewLife.XException: 解析主机redis-replicas-0.的地址失败！Name does not resolve
2023-09-09T21:11:46.269662456Z  ---> System.Net.Sockets.SocketException (00000005, 0xFFFDFFFF): Name does not resolve
2023-09-09T21:11:46.269672382Z    at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Int64 startingTimestamp)
2023-09-09T21:11:46.269684198Z    at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s, Int64 startingTimestamp)
2023-09-09T21:11:46.269694191Z    at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
2023-09-09T21:11:46.269703936Z    at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
2023-09-09T21:11:46.269712773Z    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2023-09-09T21:11:46.269720385Z --- End of stack trace from previous location ---
2023-09-09T21:11:46.269726444Z    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2023-09-09T21:11:46.269747144Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2023-09-09T21:11:46.269764653Z --- End of stack trace from previous location ---
2023-09-09T21:11:46.269778133Z    at NewLife.Net.DnsResolver.ResolveCore(String host, DnsItem item, Boolean throwError)
2023-09-09T21:11:46.269789390Z    at NewLife.Net.DnsResolver.Resolve(String h
ost)
2023-09-09T21:11:46.269799004Z    at NewLife.Net.NetUri.ParseAddress(String hostname)
2023-09-09T21:11:46.269809104Z    --- End of inner exception stack trace ---
2023-09-09T21:11:46.269818822Z    at NewLife.Net.NetUri.ParseAddress(String hostname)
2023-09-09T21:11:46.269828576Z    at NewLife.Net.NetUri.get_EndPoint()
   at NewLife.Net.NetUri.get_Port()
2023-09-09T21:11:46.269841151Z    at NewLife.Caching.Clusters.RedisReplication.GetReplications(Redis redis, IList`1 servers)
2023-09-09T21:11:46.269847376Z    at NewLife.Caching.Clusters.RedisReplication.GetNodes()
2023-09-09T21:11:46.269853574Z    at System.Threading.Tasks.Task`1.InnerInvoke()
2023-09-09T21:11:46.269859879Z    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2023-09-09T21:11:46.269866098Z --- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2023-09-09T21:11:46.269878350Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2023-09-09T21:11:46.269884573Z    --- End of inner exception stack trace ---
2023-09-09T21:11:46.269890601Z    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2023-09-09T21:11:46.269896684Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2023-09-09T21:11:46.269902845Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at NewLife.Caching.Clusters.RedisReplication.StartMonitor()
2023-09-09T21:11:46.269915130Z    at NewLife.Caching.FullRedis.InitCluster()
2023-09-09T21:11:46.269921159Z    at NewLife.Caching.FullRedis.Execute[T](String key, Func`3 func, Boolean write)
   at NewLife.Caching.Redis.SetAll[T](IDictionary`2 values, Int32 expire)

**Comment by nnhy** [comment]
server=redis.newlifex.com;port=6379;password=123456;db=3

What's your address of server？
Try again with version>=v2023.0803

**Comment by ehinolakingsley** [comment]
Ok. Thanks for the response. I use kubernetic dns cluster name. I use the master instance address and the master redirect it to one of the worker service address. It's at the point it fails. But the old version does do that. I will try the new version you mentioned now.

**Comment by ehinolakingsley** [comment]
Still the same.
[FTL] PRO PARENT-API-6SLDM iRegisterkids.Parent | One or more errors occurred. (解析主机redis-replicas-3.的地址失败！Name does not resolve)
System.AggregateException: One or more errors occurred. (解析主机redis-replicas-3.的地址失败！Name does not resolve)
 ---> NewLife.XException: 解析主机redis-replicas-3.的地址失败！Name does not resolve
2023-10-02T15:05:32.699359968Z  ---> System.Net.Sockets.SocketException (00000005, 0xFFFDFFFF): Name does not resolve
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Int64 startingTimestamp)
2023-10-02T15:05:32.699401918Z    at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s, Int64 startingTimestamp)
   at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
2023-10-02T15:05:32.699492428Z    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2023-10-02T15:05:32.699534374Z --- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2023-10-02T15:05:32.699608855Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at NewLife.Net.DnsResolver.ResolveCore(String host, DnsItem item, Boolean throwError)
   at NewLife.Net.DnsResolver.Resolve(String host)
   at NewLife.Net.NetUri.ParseAddress(String hostname)
2023-10-02T15:05:32.699754328Z    --- End of inner exception stack trace ---
   at NewLife.Net.NetUri.ParseAddress(String hostname)
   at NewLife.Net.NetUri.get_EndPoint()
2023-10-02T15:05:32.699811861Z    at NewLife.Net.NetUri.get_Port()
   at NewLife.Caching.Clusters.RedisReplication.GetReplications(Redis redis, IList`1 servers)
   at NewLife.Caching.Clusters.RedisReplication.GetNodes()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2023-10-02T15:05:32.699966738Z    --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at NewLife.Caching.Clusters.RedisReplication.StartMonitor()
   at NewLife.Caching.FullRedis.InitCluster()
   at NewLife.Caching.FullRedis.Execute[T](String key, Func`3 func, Boolean write)
   at NewLife.Caching.Redis.SetAll[T](IDictionary`2 values, Int32 expire)

**Comment by ehinolakingsley** [comment]
Can u compare the difference between v5.1.2023.203(Working) vs latest version that are not working

**Comment by nnhy** [comment]
redis.AutoDetect = false;

**Comment by ehinolakingsley** [comment]
Thanks. That fixed the issue
