### ISSUE TITLE
FullQueue一个组多个消费者同时消费经常出现这个错误

### ISSUE THREAD

**Issue by jovi-Li** [NewLifeX/NewLife.Redis#62]
11:06:20.030  8 Y - System.NullReferenceException: Object reference not set to an instance of an object.
   at NewLife.Caching.Models.PendingItem.Parse(Object[] vs) in F:\jovi\gitProjects\NewLife.Redis\NewLife.Redis\Models\PendingItem.cs:line 28
   at NewLife.Caching.RedisStream`1.Pending(String group, String startId, String endId, Int32 count) in F:\jovi\gitProjects\NewLife.Redis\NewLife.Redis\RedisStream.cs:line 447
   at NewLife.Caching.RedisStream`1.RetryAck() in F:\jovi\gitProjects\NewLife.Redis\NewLife.Redis\RedisStream.cs:line 232
   at NewLife.Caching.RedisStream`1.TakeMessageAsync(Int32 timeout, CancellationToken cancellationToken) in F:\jovi\gitProjects\NewLife.Redis\NewLife.Redis\RedisStream.cs:line 209
   at QueueDemo.FullQueue.ConsumeAsync(FullRedis redis, String topic, String group, CancellationToken token) in F:\jovi\gitProjects\NewLife.Redis\QueueDemo\FullQueue.cs:line 64

PendingItem方法报错的  
 take消息的时候为什么要执行这个        if (!group.IsNullOrEmpty()) RetryAck();  ？ 应该是这里取到空值了

**Comment by nnhy** [comment]
消费的时候，需要定时检查pending列表，如果有长时间挂起的消息，需要转移回去主队列重新消费。

这里应该是代码写得不够严谨，抛异常了，马上修正

**Comment by jovi-Li** [comment]
![image](https://user-images.githubusercontent.com/3616205/106446195-e8f50b00-64ba-11eb-80e2-4b1b60d9fca9.png)
改了这个bug还有问题 ， 这地方不能这么循环

**Comment by nnhy** [comment]
这个问题还存在吗？
