### ISSUE TITLE
多消费组可重复消费的队列，发送的消息实体中有个属性的值为""时，订阅端获取时会出错

### ISSUE THREAD

**Issue by e4ky** [NewLifeX/NewLife.Redis#67]
比如一个消息实体类：
`
public class Message{
       public string UserID { set;get;}
       public string Message { set;get;}
}
`
消息类中的Message = “” 时，在Add(T value)后，订阅端TakeMessageAsync消费时就会报

 System.NullReferenceException: Object reference not set to an instance of an object.
   at NewLife.Caching.RedisStream`1.<>c.<Parse>b__54_0(Object e)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at NewLife.Caching.RedisStream`1.Parse(Object[] vs)
   at NewLife.Caching.RedisStream`1.ReadGroupAsync(String group, String consumer, Int32 count, Int32 block, CancellationToken cancellationToken)
   at NewLife.Caching.RedisStream`1.TakeMessageAsync(Int32 timeout, CancellationToken cancellationToken)

**Comment by e4ky** [comment]
{"MessageType":1,"DeviceID":"000210","Data":{OrderID":"1","UserID":"用户编号","DetectDate":"0001-01-01"},"SourceID":"RedisMQTestTool","SendTime":"2021-04-26T20:40:42.9524861+08:00"}

比如发送这样一条消息，但当DetectDate的值为default(DateTime)时，接订阅端反序列化时就出错了。

**Comment by nnhy** [comment]
redis基础协议解析的bug，在newlife.core中已修正！

https://github.com/NewLifeX/X/commit/028f92d43696f0ba5e9f46d02b46d320c02dac07
